### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cristianco7** [ediaz23/crunchyroll-webos-stream#1]
I do everything correctly but when I run the front I get an error in the enact cmd. Can you make a better tutorial, thank you

**Comment by ediaz23** [comment]
Maybe you need to install _npm install -g @enact/cli_, could you share a screenshot to see, and thus correct the readme.

**Comment by cristianco7** [comment]
![image](https://github.com/ediaz23/crunchyroll-webos-stream/assets/95204007/f1f74318-a5a8-4ac0-b43d-c7dd2608c753)

**Comment by cristianco7** [comment]
yes it was that but when I run and log in then I get this 
![image](https://github.com/ediaz23/crunchyroll-webos-stream/assets/95204007/253b3027-39e3-4e00-9b88-034295ab6943)
![image](https://github.com/ediaz23/crunchyroll-webos-stream/assets/95204007/097c4d6e-a829-4392-82f4-01ecaf154390)

**Comment by cristianco7** [comment]
that happens when I try to play an anime

**Comment by ediaz23** [comment]
I updated the "service" submodule. Please update your local project.

can you open browser terminal to see where specifically is the error??

discover.getNext is [here](https://github.com/ediaz23/crunchyroll-webos-stream/blob/974af10803474d555bf10e3266bb340d43d6f686/src/api/discover.js#L190)

**Comment by ediaz23** [comment]
Perhaps you must delete node_modules/crunchyroll-js-api/ and make _npm install_ again.
This package crunchyroll-js-api is setting to install direct from github still.
