### ISSUE TITLE
Works well 👍 

### ISSUE THREAD

**Issue by Rucadi** [ediaz23/crunchyroll-webos-stream#2]
Thank you a lot for this app, there is one crunchyroll app in the homebrew store, but the login doesn't work.

Do you plan to upload this app to the webos homebrew repo so the discoverability of your project is improved?

Thank you very much!

**Comment by ediaz23** [comment]
Hello, thank you.

Yes, I was looking for how to publish it recently. I plan to do it tomorrow or next week, after improving non-premium accounts experience.

**Comment by ediaz23** [comment]
Can you tell me model TV and Webos Version where you tested it?

**Comment by Rucadi** [comment]
> Can you tell me model TV and Webos Version where you tested it?

LG 86QNED866RE and the version idk, from half a year probably.
