### ISSUE TITLE
black screen on version 5.X

### ISSUE THREAD

**Issue by ss456f** [ediaz23/crunchyroll-webos-stream#7]
my lg software is 5.40.45 and when i run the app it displays a black screen its not working correctly any solutions?

**Comment by ediaz23** [comment]
Do you have any other information? 
TV model?
Do you use this account normally?
How long have you had this account?
Can you share a picture or video?
Can you see your TV in your account devices like this [link](https://private-user-images.githubusercontent.com/60756686/348366820-00647840-8f24-4467-9b40-dc5e48d516b1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTI4MzksIm5iZiI6MTcyNTI5MjUzOSwicGF0aCI6Ii82MDc1NjY4Ni8zNDgzNjY4MjAtMDA2NDc4NDAtOGYyNC00NDY3LTliNDAtZGM1ZTQ4ZDUxNmIxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNTU1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTA0OTFlYjI0ODYwOGU2ODZhNDcwNzQ3NWY3MzQ1N2M3NzZiMGU4ZTJjYzA4M2YwYjEyNjJkNWVkNzkyMjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kA7VglczCfT0ctjtNYWEeOS-WA4z9PgtrNRpQmogjug)

**Comment by ss456f** [comment]
the tv model is : 43LM6370pva
the account is used normally 
and the app doesn't open just a black screen

**Comment by ediaz23** [comment]
is your account premium? 
can you post a video?
